Update patch set 3
Patch Set 3: -Auto-Submit

> Patch Set 3:
> 
> (1 comment)
> 
> Actually, last time I rolled this there were some problems with the XFA bots, so let me see if that happens again before reviewing this.

Compile error triggered by an MSVC-specific warning:

  ...
  ../../third_party/zlib/contrib/optimizations/inflate.c(107): error C2220: the following warning is treated as an error
  ../../third_party/zlib/contrib/optimizations/inflate.c(107): warning C4131: 'inflateStateCheck': uses old-style declarator
  ...

Chromium dropped MSVC support, but PDFium (and V8) are keeping it:
https://groups.google.com/a/chromium.org/d/topic/chromium-dev/fuVUxe1q6EA/discussion
https://groups.google.com/d/msg/pdfium/d7KZi_wePHs/ddrKiTiXFgAJ

Looks like the time has come for MSVC support to cost us. 😉 Chromium doesn't support MSVC, but V8 and PDFium still do. Be nice if we had a bot to check that dependencies like this compiled on MSVC...

Patch-set: 3
Reviewer: Gerrit User 7613 <7613@fca2d64a-0420-3532-b200-12848c95a47b>
Label: Auto-Submit=0
Label: Commit-Queue=0