Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Btw, did you test if this triggers the fallthrough errors, without my fix https://pdfium-review.googlesource.com/c/pdfium/+/26950 ? I tried rolling only clang yesterday and it didn't. I'm curious if we will be able to actually verify the fallthrough errors are fixed before relanding Nico's CL.

I just tried. Yes, it triggers the errors. However, there is warning that seems to have been cause by an extra FX_FALLTHROUGH:

../../core/fpdfapi/render/cpdf_renderstatus.cpp:1769:9: error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
        FX_FALLTHROUGH;

I'll send a CL to fix.

Patch-set: 3
Reviewer: Gerrit User 7035 <7035@fca2d64a-0420-3532-b200-12848c95a47b>