Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > > Patch Set 2:
> > > > 
> > > > I wonder if the test is flaky? There's full coverage here and the win_xfa_clang try bot was fine.
> > > 
> > > There's definitely flakiness involved, but I can't tell if there's something about my CL triggering that flakiness or if was just bad luck.
> > 
> > Henrique and I looked at my test and his code together, and we are not sure why this is being flaky. The plan is to hold off this CL for a bit and see if this bot fails for other CL too. Lei, let us know if you have a better suggestion.
> 
> We can hold on this for now and see if the test flakes again with some other CL. FTR, the failure was:
> 
> ../../fpdfsdk/fpdfannot_embeddertest.cpp(192): error: Value of: A
>   Actual: 255
> Expected: 51u
> Which is: 51
> Assertion failed: IsArray(), file ../../core/fpdfapi/parser/cpdf_array.cpp, line 190
> 
> Too bad there was no stack trace when the ASSERT() failed.

I think it's better to say that the failure was 1. mismatch between /all/ set and get values of RGBA, and 2. ASSERT failure.
1. The "actual" values of RGBA are the default ones when no RGBA values have been set, so I suspect it's because somehow SetNewFor and AddNew within FPDFAnnot_SetColor() failed.
2. The ASSERT failure - pretty sure it comes from AddNew within FPDFAnnot_SetRect().
But these are guesses, guess we will just wait and see for now.

Patch-set: 2