Update patch set 2
Patch Set 2:

For the record, the failure was:

[ RUN      ] FPDFAnnotEmbeddertest.CountAttachmentPoints
../../fpdfsdk/fpdfannot_embeddertest.cpp(485): error: Expected equality of these values:
  3u
    Which is: 3
  FPDFAnnot_CountAttachmentPoints(annot.get())
    Which is: 1
[  FAILED  ] FPDFAnnotEmbeddertest.CountAttachmentPoints (31 ms)

Patch-set: 2
Reviewer: Gerrit User 5045 <5045@fca2d64a-0420-3532-b200-12848c95a47b>