Update patch set 3
Patch Set 3:

> Patch Set 3: -Auto-Submit
> Compile error triggered by an MSVC-specific warning:
> 
>   ...
>   ../../third_party/zlib/contrib/optimizations/inflate.c(107): error C2220: the following warning is treated as an error
>   ../../third_party/zlib/contrib/optimizations/inflate.c(107): warning C4131: 'inflateStateCheck': uses old-style declarator
>   ...

This appears to be crrev.com/c/2156228; compiler flags probably changed in a way that stopped suppressing something important. Doing a diff now.

Patch-set: 3
Reviewer: Gerrit User 7613 <7613@fca2d64a-0420-3532-b200-12848c95a47b>
Label: Auto-Submit=0
Label: Commit-Queue=0